### PR TITLE
Create 1023.json

### PR DESCRIPTION
**Pull request by Fatman13**
Create json file for allocator [1023](https://github.com/filecoin-project/notary-governance/issues/1023) per comments [here](https://filecoinproject.slack.com/archives/C06MTBZ44P2/p1711014042534879?thread_ts=1710911760.893179&cid=C06MTBZ44P2).

Request for review. Thx! CC @willscott @clriesco

### CODE REVIEW

**Comment by willscott** [comment]
This repo is operated by the governance team, so you need sign-off by @galen-mcandrew

**Comment by Fatman13** [comment]
kk got it. thx.

**Comment by galen-mcandrew** [comment]
This should be captured in PR https://github.com/filecoin-project/Allocator-Registry/pull/7

Please check if that JSON file has the correct details, and let me know if you need additional review or changes.

**Comment by Fatman13** [comment]
kk ty

**Pull request closed without merging**
