### PR TITLE
Update 1019.json

### PR DESCRIPTION
**Pull request by Chuangshi1**
@galen-mcandrew @willscott @jbenet Hope you can help us to change new account.
f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
The Gilf can't recognize my wallet. We have tried many ways to resolve the problem. It always failed.

### CODE REVIEW

**Comment by galen-mcandrew** [comment]
Is this new address on the f2 msig? The tooling requires using the msig, and that is where the DataCap is held on-chain.

**Comment by Chuangshi1** [comment]
> Is this new address on the f2 msig? The tooling requires using the msig, and that is where the DataCap is held on-chain.

We didn't offer the msig. We just offer one old address which is f1ldkhvk55psquvhc727udmdl2tgm55exndh2meqa. But the FF team create the msig for us. f2m4ljkbqkw4rljq7mhu2xmdchnvbcuwqox4hebnq
The old address can't recognise on the sign page always, so we need to add a new address which is also list in our ledger.
We talked this problem with KZ. He told me you can help us. Thank you so much.
image
image

**Comment by Chuangshi1** [comment]
@galen-mcandrew

**Comment by Chuangshi1** [comment]
Hope we can get update from you soon. We really need to resolve the problem quickly.

**Comment by Chuangshi1** [comment]
image
image
@galen-mcandrew @Kevin-FF-USA @willscott @jbenet  It can be scroll now. But it can't show my signer address :f1ldkhvk55psquvhc727udmdl2tgm55exndh2meqa   
So hope you can help us to add the new address to the multsign.  f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri

**Comment by galen-mcandrew** [comment]
https://filfox.info/en/address/f2m4ljkbqkw4rljq7mhu2xmdchnvbcuwqox4hebnq

New address added to msig

**Comment by Chuangshi1** [comment]
Thanks. It works now.

**Pull request merged**
